### ISSUE TITLE
Incorrect night/day rendering

### ISSUE THREAD

**Issue by jmgomezpoveda** [rossengeorgiev/nite-overlay#3]
The generated overlay does not show a proper day/night overlay, nor does it correspond to the screenshot in https://github.com/rossengeorgiev/nite-overlay.

It has the shape of two stretched circles, which is a totally different shape, and not accurate at all (especially in latitudes away from the equator).

As an example: http://www.flightradar24.com/50.12,-69.61/2

I have tried the library and got similar results.

**Comment by jmgomezpoveda** [comment]
The rendering could probably use google.maps.Polygon (defined over the path of the day/night limit) instead of google.maps.Circle.

**Comment by rossengeorgiev** [comment]
Hi @jmgomezpoveda,
What you see is a fairly accurate approximation. The circles on google maps are accurately represented in the Mercator projection.

http://en.wikipedia.org/wiki/Mercator_projection#Scale_factor
https://in-the-sky.org/twilightmap.php

**Comment by jmgomezpoveda** [comment]
You are right, thanks for the information. I guess that's what I get for testing a day/night library during the March equinox.
