### ISSUE TITLE
Explanation of Twilight Calculation

### ISSUE THREAD

**Issue by KosherJava** [rossengeorgiev/nite-overlay#4]
@rossengeorgiev Thank you for what appears a very simple solution for a problem that I have seen many overly complicated solutions for. I have a question related to what appears to be the twilight calculations. From what I understand from the code, you are using a smaller earth radius for one of the overlay providing the lighter dusk layer.

`radius: this.shadow_radius * 0.96`

Can you explain how this works? As an example if I wanted to show the following:
* sunset/rise line
* Civil twilight (sun 6 degrees below the horizon) - Is this where the 0.96 comes from?
* Nautical twilight (sun 12 degrees below the horizon)
* Astronomical twilight (sun 12 degrees below the horizon)

Thanks

PS: I wish there was a way to tag this as an inquiry as opposed to an issue.

**Comment by rossengeorgiev** [comment]
Hi @KosherJava, I've chosen that value simply because it looked good.

**Comment by KosherJava** [comment]
@rossengeorgiev, Thanks for the candor. How can the overlays be changed to something that represents the realistic dusk times mentioned above?
Thanks

**Comment by rossengeorgiev** [comment]
I've updated the code and it will now draw all twilight zones. Does that work for you?

**Comment by KosherJava** [comment]
Phenomenal!
Thank you very much. I guess I can close this item now.
