### ISSUE TITLE
Refresh Limited to 1 Minute

### ISSUE THREAD

**Issue by KosherJava** [rossengeorgiev/nite-overlay#5]
The documentation in the README.md mentions
> Use refresh() method to update the overlay periodically. Perhaps via setInterval();
> setInterval(function() { nite.refresh() }, 10000); // every 10s

This is nice when you are zoomed into a map and want to see the rise/set shadows move realistically along a map. 
However due to the the way things are calculated, it will never have granularity of less than a minute. I believe that this is due to the use of `mins_past_midnight` (as well 1440 in `true_solar_time` in the code that artificially limits finer refreshes.

To test this, load the map with zoomed in so that you can see the civil twilight time and set the refresh to every 5 or 10 seconds. You will see that the line jumps about once a minute as opposed to the set refresh interval.

There is another issue in that the actual sunrise/set times on a map are a few minutes off from what the shadows would indicate. I did not yet open a bug for that under the assumption that perhaps it is impacted somewhat by this issue.

Thanks

**Comment by rossengeorgiev** [comment]
Hi @KosherJava,
You were correct, the NOAA calculations I've used were limited to minutes by the parameters you've pointed out. I've made the changes and you can refresh at rates down to milliseconds.

On the accuracy of the shadow, I'm not sure if I can get it more accurate. The values I use for the shadowed areas are very rough approximation.

**Comment by KosherJava** [comment]
@rossengeorgiev,
Thank you very much. This solved the issue.
