### ISSUE TITLE
Sunset time does not seem to factor in atmospheric refraction and possibly the solar radius

### ISSUE THREAD

**Issue by KosherJava** [rossengeorgiev/nite-overlay#6]
Hi,
I see that the calculation of the sunset time seems to not correct for atmospheric refraction (34/60 or a degree) and possibly not the solar radius (16/60 of a degree) that together add an offset of 5/6 (0.833...) degrees and delay sunset and results in an earlier sunrise. I have a hard time reading the code, and solar radius may indeed be factored in. The quick fix is to change 0 degrees for sunset to 5/6, but this does not seem to fully fix the issue. My best calculation shows that adjusting it from 0 to 34/60 (refraction) does the trick until you reach very high or low latitudes where the issue is likely a mix of Google Maps not being very accurate and general inaccuracy of such calculations. This along with the `var rad = 0.017453292519943295;` code lead me to believe that solar radius is indeed factored in. The other twilight levels are not impacted by this since the numbers already account for the level of darkness at that degree regardless of the refraction/solar radius. A quick comparison of using 34/60 to actual calculated sunsets shows the time of the shadows seems to be very accurate compared to various sunrise/set libraries.

**Comment by rossengeorgiev** [comment]
Have you looked at http://www.esrl.noaa.gov/gmd/grad/solcalc/calcdetails.html ?

**Comment by KosherJava** [comment]
@rossengeorgiev,
Yes I have seen it. Unless I misunderstand things, the code looks for the position of the sun at it's zenith, locates it's antipodal position and draws the circle (minus the angle 0 for sunset). At this overhead 90 degree zenith there is indeed no refraction, however, at the edge of the circle there certainly is. Due to refraction at sunrise and sunset, the amount of the globe that under sunlight is slightly larger than the parts in the dark. This would be 34/60 on each side. For this reason, the zero twilight should actually be shrunk by this amount. As an odd example, if the sun somehow were right over the north pole, the area 0.5666 degrees below the equator would be in sunlight due to refraction. I hope that I am clear, but please let me know if I am not. As far as the link, there is an error when they mention refraction of 0.833 (50/60), the graph that they link to from that page at http://www.esrl.noaa.gov/gmd/grad/solcalc/atmosrefr.gif is accurate and illustrates the 0.566. The 0.833 is the combination of refraction (at sunrise/set) and the solar radius. Also see https://en.wikipedia.org/wiki/Atmospheric_refraction where the 34' figure is mentioned. This figure is also present in Calendrical Calculations and other sources.

**Comment by rossengeorgiev** [comment]
I just need to reduce the shadowed area by 0.6 degrees, without touching twilight, correct?

**Comment by KosherJava** [comment]
Correct, but I suggest that you use 5/6 or 0.566666 since at the equator the difference between 0.6 and 0.566666 is almost 4 km.
Thanks

**Comment by rossengeorgiev** [comment]
Thanks for the help @KosherJava
