### ISSUE TITLE
Overlay doesn't stop at map edge

### ISSUE THREAD

**Issue by MagixInTheAir** [rossengeorgiev/nite-overlay#7]
When scrolling the map through it's upper or bottom edge, over the poles, the main night shadow continues but not the other, lighter shadows. It is really unesthetic for applications where unzooming is crucial, for instance i have an overlay to plot the path of a satellite and so it can go over poles and it looks really bad :/

Thank you very much

**Comment by rossengeorgiev** [comment]
I'm confused, are you talking about this?

![shadow](https://cloud.githubusercontent.com/assets/2720787/22552265/1315399a-e950-11e6-9dfe-80dc2ab1d3c7.png)

The shadow is correctly projected. I see no problem. The tile edge ends at 85 degree latitude. The poles are not visible in the tiled area. Any point >85 degree will be located somewhere outside the tile area.

**Comment by MagixInTheAir** [comment]
Yes, I am talking about this, and I think the grey area over/under the map should be left with the same color everywhere if possible :) I agree the shadow is correctly projected though

**Comment by rossengeorgiev** [comment]
I disagree. The gray area is still part of the map, and things above 85 degrees can will still be drawn, so it makes sense the shadow to be drawn as well.
